//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int id { get; set; }
        public Nullable<int> from_account_id { get; set; }
        public Nullable<int> to_account_id { get; set; }
        public string branch_id { get; set; }
        public Nullable<System.DateTime> date_of_trans { get; set; }
        public Nullable<double> amount { get; set; }
        public string pin { get; set; }
        public string employee_id { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
